// nextjs-pages/github-oauth/pages/index.tsx
import { validateRequest } from "@/lib/auth";
import { useRouter } from "next/router";

import type {
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	InferGetServerSidePropsType
} from "next";
import type { User } from "lucia";

export async function getServerSideProps(context: GetServerSidePropsContext): Promise<
	GetServerSidePropsResult<{
		user: User;
	}>
> {
	const { user } = await validateRequest(context.req, context.res);
	if (!user) {
		return {
			redirect: {
				permanent: false,
				destination: "/login"
			}
		};
	}
	return {
		props: {
			user
		}
	};
}

export default function Page({ user }: InferGetServerSidePropsType<typeof getServerSideProps>) {
	const router = useRouter();
	return (
		<>
			<h1>Hi, {user.username}!</h1>
			<p>Your user ID is {user.id}.</p>
			<form
				method="post"
				action="/api/logout"
				onSubmit={async (e) => {
					e.preventDefault();
					const formElement = e.target as HTMLFormElement;
					await fetch(formElement.action, {
						method: formElement.method
					});
					router.push("/login");
				}}
			>
				<button>Sign out</button>
			</form>
		</>
	);
}

// nuxt/github-oauth/pages/index.vue
<script lang="ts" setup>
definePageMeta({
	middleware: ["protected"]
});

const user = useAuthenticatedUser();

async function logout() {
	await $fetch("/api/logout", {
		method: "POST"
	});
	await navigateTo("/login");
}
</script>

<template>
	<h1>Hi, {{ user.username }}!</h1>
	<p>Your user ID is {{ user.id }}.</p>
	<form @submit.prevent="logout">
		<button>Sign out</button>
	</form>
</template>
