// qwik-city/username-and-password/src/routes/signup/index.tsx
import { component$ } from "@builder.io/qwik";
import {
  type DocumentHead,
  routeAction$,
  zod$,
  z,
  Form,
  routeLoader$,
  Link,
} from "@builder.io/qwik-city";
import { auth } from "~/lib/lucia";
import { SqliteError } from "better-sqlite3";

export const useUserLoader = routeLoader$(async (event) => {
  const authRequest = auth.handleRequest(event);
  const session = await authRequest.validate();
  if (session) {
    throw event.redirect(303, "/");
  }

  return {};
});

export const useSignupUser = routeAction$(
  async (values, event) => {
    try {
      const authRequest = auth.handleRequest(event);
      const user = await auth.createUser({
        key: {
          providerId: "username", // auth method
          providerUserId: values.username.toLowerCase(), // unique id when using "username" auth method
          password: values.password, // hashed by Lucia
        },
        attributes: {
          username: values.username,
        },
      });
      const session = await auth.createSession({
        userId: user.userId,
        attributes: {},
      });
      authRequest.setSession(session); // set session cookie
    } catch (e) {
      // check for unique constraint error in user table
      if (e instanceof SqliteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
        return event.fail(400, {
          message: "Username already taken",
        });
      }
      return event.fail(500, {
        message: "An unknown error occurred",
      });
    }

    // redirect to
    // make sure you don't throw inside a try/catch block!
    throw event.redirect(303, "/");
  },
  zod$({
    username: z.string().min(2),
    password: z.string().min(5),
  }),
);

export default component$(() => {
  const signupUserAction = useSignupUser();
  return (
    <>
      <Form
        action={signupUserAction}
        class="form-control mx-auto mt-32 max-w-lg"
      >
        <label for="username" class="label">
          Username
        </label>
        <input id="username" name="username" class="input bg-base-200" />

        <label for="password" class="label">
          Password
        </label>
        <input
          type="password"
          id="password"
          name="password"
          class="input bg-base-200"
        />

        <button type="submit" class="btn btn-primary my-2">
          Signup
        </button>

        <p class="py-4">
          Already have an account?{" "}
          <Link href="/login/" class="link-primary">
            Login
          </Link>
        </p>

        {signupUserAction.value?.message && (
          <p class="font-bold text-error">{signupUserAction.value.message}</p>
        )}
      </Form>
    </>
  );
});

export const head: DocumentHead = {
  title: "Signup Page",
  meta: [
    {
      name: "description",
      content: "This is the signup page",
    },
  ],
};

// solidstart/username-and-password/src/routes/signup.tsx
import { action, redirect, useSubmission } from "@solidjs/router";
import { generateId } from "lucia";
import { Argon2id } from "oslo/password";
import { Show, getRequestEvent } from "solid-js/web";
import { lucia } from "~/lib/auth";
import { db } from "~/lib/db";
import { SqliteError } from "better-sqlite3";
import { setCookie } from "vinxi/http";

export default function Index() {
	const submission = useSubmission(signup);
	return (
		<>
			<h1>Create an account</h1>
			<form method="post" action={signup}>
				<label for="username">Username</label>
				<input name="username" id="username" />
				<br />
				<label for="password">Password</label>
				<input type="password" name="password" id="password" />
				<br />
				<button>Continue</button>
				<Show when={submission.result}>{(result) => <p>{result().message}</p>}</Show>
			</form>
			<a href="/login">Sign in</a>
		</>
	);
}

const signup = action(async (formData: FormData) => {
	"use server";
	const username = formData.get("username");
	if (
		typeof username !== "string" ||
		username.length < 3 ||
		username.length > 31 ||
		!/^[a-z0-9_-]+$/.test(username)
	) {
		return new Error("Invalid username");
	}
	const password = formData.get("password");
	if (typeof password !== "string" || password.length < 6 || password.length > 255) {
		return new Error("Invalid password");
	}

	const hashedPassword = await new Argon2id().hash(password);
	const userId = generateId(15);

	try {
		db.prepare("INSERT INTO user (id, username, password) VALUES(?, ?, ?)").run(
			userId,
			username,
			hashedPassword
		);

		const session = await lucia.createSession(userId, {});

		const cookie = lucia.createSessionCookie(session.id);

		setCookie(cookie.name, cookie.value, cookie.attributes);
	} catch (e) {
		if (e instanceof SqliteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
			return new Error("Username already used");
		}
		return new Error("An unknown error occurred");
	}
	throw redirect("/");
});
